
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# logger -> symlink to ramdisk

# db is moved to ramdisk
recorder:
  purge_keep_days: 1 
  db_url: sqlite:////var/ha-data/homeassistant.db
  exclude:
    domains:
      - automation
      - device_tracker
      - updater
      - group
      - input_number
      - remote

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
script: !include scripts.yaml
automation: !include_dir_merge_list automations

homeassistant:
  packages: !include_dir_named packages
