
- alias: Set Bathroom Lighting on
  trigger:
    - platform: state
      entity_id: switch.bathroom_lighting
      to: 'on'
  action:
    - service: switch.turn_on
      entity_id: switch.sonoff_3

- alias: Set Bathroom Lighting off
  trigger:
    - platform: state
      entity_id: switch.bathroom_lighting
      to: 'off'
  action:
    - service: switch.turn_off
      entity_id: switch.sonoff_3

- alias: Set Bathroom Light on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f0839e
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automation_enabled
      state: 'on' 
  action:
    - service: switch.turn_on
      data_template:
        entity_id: > 
          {% if states('input_select.scene_bathroom') == 'Cozy' %}
          switch.bathroom_mirror_lighting
          {% else %}
          switch.bathroom_lighting, switch.sonoff_3
          {% endif %}

- alias: Set Bathroom Light off  
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f0839e
      to: 'off'
      for: '00:03:00'
  #need condition for shaving / taking a bath
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.bathroom_lighting, switch.sonoff_3, switch.bathroom_mirror_lighting

