#binary_sensor.motion_sensor_158d0003cd87cb
#
- alias: Set Corridor Light on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003cd87cb
      to: 'on'
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automation_enabled
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.corridor_lighting

- alias: Set Corridor Light off   
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003cd87cb
      to: 'off'
      #for: '00:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.corridor_lighting
