# automation for landing light in landing.yaml

# switch light on when motion hall detected and lighting enabled
#
- alias: Set Hallway Light on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c944
      to: 'on'
    - platform: state
      entity_id: input_boolean.lighting_automation_enabled
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automation_enabled
      state: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.hallway_lighting

- alias: Set Hallway Light off   
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c944
      to: 'off'
      #for: '00:02:00'
  condition:
    - condition: template
      value_template: "{{ states('input_select.scene_hallway') != 'Visitors'}}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hallway_lighting

- alias: Set frontdoor Light on
  trigger:
    - platform: state
      entity_id: input_select.scene_hallway
      to: 'Visitors'
    - platform: state
      entity_id: input_boolean.lighting_automation_enabled
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automation_enabled
      state: 'on'
    - condition: template
      value_template: "{{ states('input_select.scene_hallway') == 'Visitors'}}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.frontdoor_lighting, switch.hallway_lighting

- alias: Set Frontdoor Lighting off
  trigger:
    - platform: state
      entity_id: input_select.scene_hallway
    - platform: state
      entity_id: input_boolean.lighting_automation_enabled
  condition:
    condition: or
    conditions:
      - condition: state
        entity_id: input_boolean.lighting_automation_enabled
        state: 'on'
      - condition: template
        value_template: "{{ states('input_select.scene_hallway') != 'Visitor'}}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.frontdoor_lighting, switch.hallway_lighting

