# switch light on when motion hall detected and lighting enabled
#
- alias: Set Hallway Light on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c944
      to: 'on'
    - platform: state
      entity_id: variable.lighting_automation_enabled
  condition:
    - condition: template
      value_template: "{{ (states('variable.lighting_automation_enabled')|int) == 1 }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hallway_lighting
- alias: Set Hallway Light off   
  trigger:
    - platform: state
      entity_id: switch.hallway_lighting
      to: 'on'
      for: '00:02:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.hallway_lighting

- alias: Detect Wake up Mode
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c944
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:00:00'
        before: '13:00:00'
      - condition: state
        entity_id: input_select.scene_living
        state: 'Sleeping'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_living
        option: 'Waking up'
