
- alias: Set Kitchen Light on Motion
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c772
      to: 'on'
    - platform: state
      entity_id: input_boolean.lighting_automation_enabled
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.lighting_automation_enabled
        state: 'on'
      - condition: template
        value_template: "{{ states('input_select.scene_living') != 'Movie' and states('input_select.scene_living') != 'Cozy' }}"
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.kitchen_lighting

- alias: Set Kitchen Light off Motion  
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f9c772 
      to: 'off'
  condition: 
    condition: template
    value_template: "{{ states('input_select.scene_living') != 'Cleaning' }}"
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.kitchen_lighting
        
