- alias: Lighting Automation Enable
  trigger:
    - platform: time_pattern 
      minutes: "/1"
    - platform: sun
      event: sunset
      offset: "-00:30:00"
  action:
    - service_template: > 
          {% if (states('sensor.steensel_irradiance')|int < 60 and states('sensor.steensel_irradiance')|int != 0) or states('sensor.illumination_50ec50c5311e')|int < 500 %}
          input_boolean.turn_on
          {% else %}
          input_boolean.turn_off
          {% endif %}
      data:
        entity_id: input_boolean.lighting_automation_enabled

