
#TODO: problem we don't know the actual state of the remote devices
#TODO: audio is not correctly initialized -> add delay to start
- alias: Set Media Movie
  trigger:
    - platform: state
      entity_id: input_select.scene_living
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: "{{ trigger.from_state.state == 'Movie' }}"
      - condition: template
        value_template: "{{ trigger.to_state.state == 'Movie' }}"
  action:
    - service: script.beamer_toggle_onoff 
    # wait a while for media to come up from hybernation
    - delay: 00:00:10
    - service: script.speakers_toggle_onoff
