#binary_sensor.motion_sensor_158d0003cd887f


- alias: Detect Waking up
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0003cd887f
      to: 'on'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '05:00:00'
        before: '13:00:00'
      - condition: state
        entity_id: input_select.scene_living
        state: 'Out'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_living
        option: 'Normal'

