- alias: Living Sockets Scene On
  trigger:
    - platform: state
      entity_id: input_select.scene_living
    - platform: state
      entity_id: input_boolean.lighting_automation_enabled
  condition:
    - condition: state
      entity_id: input_boolean.lighting_automation_enabled
      state: 'on'
    - condition: state
      entity_id: input_select.scene_living
      state: 'Normal'
  action:
    - service_template: switch.turn_on 
      data_template: 
        entity_id: switch.living_socket_right_1

- alias: Living Socket Scene Off
  trigger:
    - platform: state
      entity_id: input_select.scene_living
  # add condition not cozy
  action:
    - service: switch.turn_off
      data_template: 
        entity_id: >
          {% if states('input_select.scene_living') != 'Normal' %}
          switch.living_socket_right_1
          {% endif %}
