- alias: Desktop on set living
  trigger:
    - platform: state
      entity_id: switch.media
      to: 'on'
  action:
    - service: input_select.select_option
      data:
        entity_id: input_select.scene_living
        option: 'Movie'
