- alias: Set Toilet Light on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f08322
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.toilet_lighting

- alias: Set Toilet Light off   
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f08322
      to: 'off'
      #for: '00:05:00'
  action:
    - service: switch.turn_off
      data:
        entity_id: switch.toilet_lighting 


