- alias: Set Toilet Light and Ventilation on
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002f08322
      to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: switch.toilet_lighting
    - service: switch.turn_on
      data: 
        entity_id: switch.ventilation
- alias: Set Toilet Light and Ventilation off   
  trigger:
    - platform: state
      entity_id: switch.toilet_lighting
      to: 'on'
      for: '00:05:00'
    - platform: state
      entity_id: switch.ventilation
      to: 'on'
      for: '00:05:00'
  action:
    - service: switch.turn_off
      data_template:
        entity_id: "{{trigger.entity_id}}"


