

input_number:
  living_irh_max_temperature:
    min: 5
    max: 70
    step: 0.5
  living_irh_zone_1_correction:
    min: -2
    max: 2
    step: 0.1
  living_irh_zone_2_correction:
    min: -2
    max: 2
    step: 0.1
  living_irh_zone_3_correction:
    min: -2
    max: 2
    step: 0.1
  living_irh_zone_4_correction:
    min: -2
    max: 2
    step: 0.1
  living_irh_delta_4_zones:
    min: 0
    max: 10
    step: 0.5
  living_irh_delta_3_zones:
    min: 0
    max: 10
    step: 0.5
  living_irh_delta_2_zones:
    min: 0
    max: 10
    step: 0.5
  living_irh_delta_1_zones:
    min: 0
    max: 10
    step: 0.5

input_select:
  living_irh_heating_profile:
    options:
      - Very slow
      - Slow
      - Normal
      - Fast
      - Very Fast

variable:
  living_irh_multiplier:
    value: 1
  living_irh_active_zones:
    value: 0
    attributes:
      priority: [1,3,2,4]

sensor:
  - platform: template
    sensors:
      living_irh_zone_1_temperature:
        friendly_name: "Corridor Floor Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ ((states('sensor.ir_heating_temp_ds18b20_2_temperature')|float) + (states('input_number.living_irh_zone_1_correction')|float))|round(2) }}"
      living_irh_zone_2_temperature:
        friendly_name: "Lounge Floor Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ ((states('sensor.ir_heating_temp_ds18b20_3_temperature')|float) + (states('input_number.living_irh_zone_2_correction')|float))|round(2) }}"
      living_irh_zone_3_temperature:
        friendly_name: "Stove Floor Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ ((states('sensor.ir_heating_temp_ds18b20_1_temperature')|float) + (states('input_number.living_irh_zone_3_correction')|float))|round(2) }}"
      living_irh_zone_4_temperature:
        friendly_name: "Kitchen Floor Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ ((states('sensor.ir_heating_temp_ds18b20_4_temperature')|float) + (states('input_number.living_irh_zone_4_correction')|float))|round(2) }}"

automation:
  - alias: Heating Profile
    trigger:
      - platform: state
        entity_id: input_select.living_irh_heating_profile
      - platform: state
        entity_id: sensor.living_thermostat_delta
    action:
      - service: variable.set_variable
        data:
          variable: living_irh_multiplier
          value_template: >
            {% if states('input_select.living_irh_heating_profile') == 'Very slow' %}
            2
            {% elif states('input_select.living_irh_heating_profile') == 'Slow' %}
            1.5
            {% elif states('input_select.living_irh_heating_profile') == 'Normal' %}
            1
            {% elif states('input_select.living_irh_heating_profile') == 'Fast' %}
            0.5
            {% elif states('input_select.living_irh_heating_profile') == 'Very Fast' %}
            0.001
            {% else %}
            1
            {% endif %}
      - service: variable.set_variable
        data:
          variable: living_irh_active_zones
          value_template: >
            {% if (states('sensor.living_thermostat_delta')|float) > ((states('variable.living_irh_multiplier')|float) * (states('input_number.living_irh_delta_3_zones')|float)) %}
            4
            {% elif (states('sensor.living_thermostat_delta')|float) > ((states('variable.living_irh_multiplier')|float) * (states('input_number.living_irh_delta_2_zones')|float)) %}
            3
            {% elif (states('sensor.living_thermostat_delta')|float) > ((states('variable.living_irh_multiplier')|float) * (states('input_number.living_irh_delta_1_zones')|float)) %}
            2
            {% else %}
            1
            {% endif %}
  - alias: IR Heating
    trigger:
      - platform: state
        entity_id: 
          - sensor.living_irh_zone_1_temperature
          - sensor.living_irh_zone_2_temperature
          - sensor.living_irh_zone_3_temperature
          - sensor.living_irh_zone_4_temperature
      - platform: state
        entity_id: variable.living_irh_multiplier
      - platform: state
        entity_id: sensor.living_thermostat_delta
    action:
      - service_template: >
          {% if (states('sensor.living_irh_zone_1_temperature')|float) >= (states('input_number.living_irh_max_temperature')|float) %}
          switch.turn_off
          {% elif (states('sensor.living_thermostat_delta')|float) > 0 %}
          {% for item in state_attr('variable.living_irh_active_zones','priority') %}
          {% if item == 1 %}
          {% if loop.index <= states('variable.living_irh_active_zones')|int %}
          switch.turn_on
          {% else %}
          switch.turn_off
          {% endif %}
          {% endif %}
          {% endfor %}
          {% else %}
          switch.turn_off
          {% endif %} 
        data:
          entity_id: switch.ir_zone_1
      - service_template: >
          {% if (states('sensor.living_irh_zone_2_temperature')|float) >= (states('input_number.living_irh_max_temperature')|float) %}
          switch.turn_off
          {% elif (states('sensor.living_thermostat_delta')|float) > 0 %}
          {% for item in state_attr('variable.living_irh_active_zones','priority') %}
          {% if item == 2 %}
          {% if loop.index <= states('variable.living_irh_active_zones')|int %}
          switch.turn_on
          {% else %}
          switch.turn_off
          {% endif %}
          {% endif %}
          {% endfor %}
          {% else %}
          switch.turn_off
          {% endif %} 
        data:
          entity_id: switch.ir_zone_2   
      - service_template: >
          {% if (states('sensor.living_irh_zone_3_temperature')|float) >= (states('input_number.living_irh_max_temperature')|float) %}
          switch.turn_off
          {% elif (states('sensor.living_thermostat_delta')|float) > 0 %}
          {% for item in state_attr('variable.living_irh_active_zones','priority') %}
          {% if item == 3 %}
          {% if loop.index <= states('variable.living_irh_active_zones')|int %}
          switch.turn_on
          {% else %}
          switch.turn_off
          {% endif %}
          {% endif %}
          {% endfor %}
          {% else %}
          switch.turn_off
          {% endif %}
        data:
          entity_id: switch.ir_zone_3
      - service_template: >
          {% if (states('sensor.living_irh_zone_4_temperature')|float) >= (states('input_number.living_irh_max_temperature')|float) %}
          switch.turn_off
          {% elif (states('sensor.living_thermostat_delta')|float) > 0 %}
          {% for item in state_attr('variable.living_irh_active_zones','priority') %}
          {% if item == 4 %}
          {% if loop.index <= states('variable.living_irh_active_zones')|int %}
          switch.turn_on
          {% else %}
          switch.turn_off
          {% endif %}
          {% endif %}
          {% endfor %}
          {% else %}
          switch.turn_off
          {% endif %}
        data:
          entity_id: switch.ir_zone_4
