#device_tracker:
#  - platform: nmap_tracker
#    hosts: 192.168.1.0/24

switch:
  - platform: wake_on_lan
    mac_address: "ac:9e:17:4d:06:05"
    name: Desktop
    host: 192.168.1.13 
    turn_off:
      service: shell_command.turn_off_desktop
  - platform: wake_on_lan
    mac_address: "78:24:af:41:c7:8a"
    name: Media
    host: 192.168.1.14
    turn_off:
      service: shell_command.turn_off_media

shell_command:
  turn_off_desktop: 'ssh homeassistant@192.168.1.13 sudo pm-suspend'
  turn_off_media: 'ssh homeassistant@192.168.1.14 sudo pm-suspend'

automation:
  - alias: Devices Living Scene Movie
    trigger:
      - platform: state
        entity_id: input_select.scene_living
    action:
      - service_template: > 
          {% if states('input_select.scene_living') == 'Movie' %}
          switch.turn_on
          {% else %}
          switch.turn_off
          {% endif %}
        entity_id: switch.media
      - service_template: >
          {% if states('input_select.scene_living') == 'Movie' %}
          switch.turn_off
          {% else %}
          switch.turn_on
          {% endif %}
        entity_id: switch.desktop
