

input_select:
  scene_home:
    name: Home Scene
    options:
      - Normal
      - Holiday
      - Out
  scene_living:
    name: Living Scene
    options:
      - Waking up
      - Sleeping
      - Working
      - Cozy
      - Movie
      - Out
      - Cleaning
  scene_hallway:
    name: Hallway Scene
    options:
      - Normal
      - Visitors
      - Out
  scene_bedroom:
    name: Bedroom Scene
    options:
      - Normal
      - Cozy
      - Out
  scene_bathroom:
    name: Bathroom Scene
    options:
      - Waking up
      - Bedtime 
      - Nightwalker 
      - Cozy
      - Out


#REMARK: only automate others scenes here. We are using a bottom up approach        
        #automation:
#  - alias: Automation Living
#    trigger:
#      - platform: state
#        entity_id: input_select.living_scene
#    action:
#      - service: 
input_text:
  scene_living_previous:
    name: Scene Living Previous State

automation:
  - alias: Scene Living Previous State Auto
    trigger: 
      platform: state
      entity_id: input_select.scene_living
    action:
      service: input_text.set_value
      data_template:
        entity_id: input_text.scene_living_previous
        value: "{{trigger.from_state.state}}"
